fun main() {
    println("Computing the Transpose, Determiant and Inverse of a 3 by 3 matrix.")
    println("Enter matrix values\n")
    print("enter first value in row 1: ")
    val number1:Double = readLine()!!.toDouble()
    print("enter second value in row 1: ")
    val number2:Double = readLine()!!.toDouble()
    print("enter third value in row 1: ")
    val number3:Double = readLine()!!.toDouble()
    print("enter first value in row 2: ")
    val number4:Double = readLine()!!.toDouble()
    print("enter second value in row 2: ")
    val number5:Double = readLine()!!.toDouble()
    print("enter third value in row 2: ")
    val number6:Double = readLine()!!.toDouble()
    print("enter first value in row 3: ")
    val number7:Double = readLine()!!.toDouble()
    print("enter second value in row 3: ")
    val number8:Double = readLine()!!.toDouble()
    print("enter third value in row 3: ")
    val number9:Double = readLine()!!.toDouble()
    println("\n\nthe transpose of the matrix is\n")
    println("\t[$number1, $number4, $number7]\n\t[$number2, $number5,$number8]\n\t[$number3, $number6, $number9]")
    println("\n\nthe determinant of the matrix is\n")
    val a2:Double = (number1 * number5 * number9) + (number2 * number6 * number7) + (number3 * number4 * number8)
    val b2:Double = (number1 * number6 * number8) + (number2 * number4 * number9) + (number3 * number5 * number7)
    val c2:Double = a2 - b2
    println("\t$c2\n\nthe inverse of the matrix is\n")
    val a3:Double = (number5 * number9) - (number8 * number6)
    val b3:Double = (number4 * number9) - (number7 * number6)
    val c3:Double = (number4 * number8) - (number7 * number5)
    val d3:Double = (number2 * number9) - (number8 * number3)
    val e3:Double = (number1 * number9) - (number7 * number3)
    val f3:Double = (number1 * number8) - (number7 * number2)
    val g3:Double = (number2 * number6) - (number5 * number3)
    val h3:Double = (number1 * number6) - (number4 * number3)
    val i3:Double = (number1 * number5) - (number4 * number2)
    val a4:Double = a3 * (1 / c2)
    val b4:Double = -d3 * (1 / c2)
    val c4:Double = g3 * (1 / c2)
    val d4:Double = -b3 * (1 / c2)
    val e4:Double = e3 * (1 / c2)
    val f4:Double = -h3 * (1 / c2)
    val g4:Double = c3 * (1 / c2)
    val h4:Double = -f3 * (1 / c2)
    val i4:Double = i3 * (1 / c2)
    println("\t[$a4, $b4, $c4]\n\t[$d4, $e4, $f4]\n\t[$g4, $h4, $i4]")
}
